### PR TITLE
Allow Symfony 4

### PR DESCRIPTION
**Pull request by dunglas**
Allow to use the bundle with Symfony 4.

### CODE REVIEW

**Comment by dunglas** [comment]
Needs #80 to be green.

**Comment by SergeC** [comment]
@dunglas @Seldaek can you tag a new version? I can't use it with SF4 due to an error:

`composer require nelmio/cors-bundle
Using version ^1.5 for nelmio/cors-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nelmio/cors-bundle 1.5.3 requires symfony/framework-bundle ^2.7 || ^3.0 -> satisfiable by `

**Comment by dunglas** [comment]
I can’t 🤗

**Comment by Shine-neko** [comment]
@Seldaek please ?

**Pull request merged**
