### PR TITLE
Optional debug logging

### PR DESCRIPTION
**Pull request by 4c0n**
Finding out what is going wrong in prod environments can be tricky sometimes.
This PR allows an optional logger to be passed which enables a debug log.

Now finding out what's happening is a breeze.

### CODE REVIEW

**Comment by rijnhard** [comment]
Seriously the amount of hours I'm spending on debugging this... can this please be merged?

**Comment by Seldaek** [comment]
Thanks - makes sense. I'd appreciate  if anyone has time to send a README PR to add an example of how this can be configured to get logging enable though

**Comment by NikoGrano** [comment]
I can see this being a really useful feature and just found it out via changelog. However, when something ain't documented, nobody is using it.

Currently, I am "reverse engineering" this feature to get it working...

@4c0n Would you mind to share us how you intended this feature to be used?

**Comment by 4c0n** [comment]
> I can see this being a really useful feature and just found it out via changelog. However, when something ain't documented, nobody is using it.
> 
> Currently, I am "reverse engineering" this feature to get it working...
> 
> @4c0n Would you mind to share us how you intended this feature to be used?

It's really easy, you override the service of the bundle and have your logger service injected.

**Comment by NikoGrano** [comment]
This is the approach I did, however, it is vulnerable to any BC changes. A better approach would be having the option to set `logger` in the configuration of the bundle. I totally understand if you are lacking time to implement it.

When possible, would you mind still documenting this?

In addition to this, adding logging also here, wouldn't hurt. For example, I had a case where one of the required headers wasn't allowed.

https://github.com/nelmio/NelmioCorsBundle/blob/b111f4bc24e1f6c24e9f5ec66951561e433b5a03/EventListener/CorsListener.php#L248-L252

**Comment by 4c0n** [comment]
> This is the approach I did, however, it is vulnerable to any BC changes. A better approach would be having the option to set `logger` in the configuration of the bundle. I totally understand if you are lacking time to implement it.
> 
> When possible, would you mind still documenting this?
> 
> In addition to this, adding logging also here, wouldn't hurt. For example, I had a case where one of the required headers wasn't allowed.
> 
> https://github.com/nelmio/NelmioCorsBundle/blob/b111f4bc24e1f6c24e9f5ec66951561e433b5a03/EventListener/CorsListener.php#L248-L252

BC changes should be in new major versions only, in which case you should review if your setup is compatible with the new version regardless.
I don't use this bundle anymore and I would suggest that you contribute the changes you envision yourself. I contributed this, because for me these changes were sufficient to solve the issues I was facing, however I had to use a fork and go through a lot more effort than I would have wished to find out what exactly was happening.
Mind you it took a really long time before this was merged and I have lost interest in the meantime.

**Comment by nickbr-icapps** [comment]
@4c0n can you give an example of how we can overwrite the service to pass the monolog logger? Thanks!

**Pull request merged**
