### PR TITLE
Allow regex in allow_origin option by setting origin_regex to `true`

### PR DESCRIPTION
**Pull request by omnidan**

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks

**Comment by Seldaek** [comment]
Just changed the readme a bit because if you simply turn this option on, then `example.org` becomes a valid match for `example.org.evil.com` so that's kinda dangerous. https://github.com/nelmio/NelmioCorsBundle/commit/4157b90bf5fa7a0ed06ffa93d5613763acf50848

**Comment by omnidan** [comment]
Can the release in composer be expected anytime soon? I'm using my fork for a production project right now and would like to switch back to the official branch as soon as possible.

And thanks for adding that, you're right, that is really dangerous and you should always use proper regex, that's why I made the origin_regex option and didn't just switch the whole thing to regex.

**Comment by Seldaek** [comment]
1.4 is out

**Pull request merged**
